language: ruby
rvm:
    - 2.1.0
    - jruby-18mode
    - jruby-19mode
    - rbx-2
    - ruby-head
    - jruby-head
matrix:
    allow_failures:
        - rvm: jruby-head
branches:
    only:
        - develop
